format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

add_newline = false

[directory]
style = "bold white"


[line_break]
disabled = true

[cmd_duration]
disabled = true

[character]
success_symbol = "[➜](bold white) "
error_symbol = "[➜](bold red) "

[git_branch]
format = "[$symbol$branch]($style) "
style = "red"
