format = """
$username\
$hostname\
$directory\
$git_commit\
$git_state\
$git_status\
$character"""

add_newline = false

[username]
format = "[$user@]($style)"
show_always = true

[hostname]
format = "[$hostname:]($style)"
ssh_only = false
style = "bold yellow"

[directory]
format = "[$path]($style)"
style = "white"
truncation_length = 15
truncate_to_repo = false

[line_break]
disabled = true

[cmd_duration]
disabled = true

[character]
success_symbol = "[\\$](white)"
error_symbol = "[\\$](red)"

[git_status]
format = '([$all_status$ahead_behind]($style))'
