format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

add_newline = false

[directory]
format = '[$path]($style)'
style = "white"
truncation_length = 15
truncate_to_repo = true

[line_break]
disabled = true

[cmd_duration]
disabled = true

[character]
success_symbol = "[ ➜](white)"
error_symbol = "[ ➜](red)"

[git_branch]
format = '[\([$branch](red)\)]($style)'
style = "white"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "red"
